/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class Caching {
    public static gwallet_backend_netstandard.gwallet.backend.CachedNetworkData importFromJson(java.lang.String cacheData) {
        com.sun.jna.Pointer __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Caching_ImportFromJson(cacheData);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new gwallet_backend_netstandard.gwallet.backend.CachedNetworkData(__ret));
    }

    public static java.lang.String exportToJson(gwallet_backend_netstandard.gwallet.backend.CachedNetworkData newCachedData) {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Caching_ExportToJson(newCachedData == null ? null : newCachedData.__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public static void saveSnapshot(gwallet_backend_netstandard.gwallet.backend.CachedNetworkData newCachedData) {
        gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Caching_SaveSnapshot(newCachedData == null ? null : newCachedData.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    static java.lang.String getlastCacheFile() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Caching_get_lastCacheFile();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
