/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend;

import mono.embeddinator.*;
import com.sun.jna.*;

public class DeserializableValueInfo {
    public com.sun.jna.Pointer __object;

    public DeserializableValueInfo(com.sun.jna.Pointer object) { this.__object = object; }

    public DeserializableValueInfo(java.lang.String version, java.lang.String typeName) {
        __object = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_DeserializableValueInfo_new(version, typeName);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getVersion() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_DeserializableValueInfo_get_Version(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getTypeName() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_DeserializableValueInfo_get_TypeName(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
