/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend;

import mono.embeddinator.*;
import com.sun.jna.*;

public abstract interface IAccount {
    public gwallet_backend_netstandard.gwallet.backend.Currency getCurrency();

    public java.lang.String getPublicAddress();

    public com.sun.jna.Pointer __getObject();
}
