/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class IAccountImpl implements gwallet_backend_netstandard.gwallet.backend.IAccount {
    public com.sun.jna.Pointer __object;

    public IAccountImpl(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    @Override
    public gwallet_backend_netstandard.gwallet.backend.Currency getCurrency() {
        com.sun.jna.Pointer __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_IAccount_get_Currency(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new gwallet_backend_netstandard.gwallet.backend.Currency(__ret));
    }

    @Override
    public java.lang.String getPublicAddress() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_IAccount_get_PublicAddress(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
