/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class Infrastructure {
    public static void setupSentryHook() {
        gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Infrastructure_SetupSentryHook();
        mono.embeddinator.Runtime.checkExceptions();
    }

    static java.lang.String getsentryUrl() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Infrastructure_get_sentryUrl();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
