/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ReadOnlyAccount implements gwallet_backend_netstandard.gwallet.backend.IAccount {
    public com.sun.jna.Pointer __object;

    public ReadOnlyAccount(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    public ReadOnlyAccount(gwallet_backend_netstandard.gwallet.backend.Currency currency, java.lang.String publicAddress) {
        __object = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_ReadOnlyAccount_new(currency == null ? null : currency.__object, publicAddress);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
