/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend;

import mono.embeddinator.*;
import com.sun.jna.*;

public class TransferAmount {
    public com.sun.jna.Pointer __object;

    public TransferAmount(com.sun.jna.Pointer object) { this.__object = object; }

    public TransferAmount(java.math.BigDecimal valueToSend, java.math.BigDecimal idealValueRemainingAfterSending) {
        __object = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_TransferAmount_new(new mono.embeddinator.Decimal(valueToSend), new mono.embeddinator.Decimal(idealValueRemainingAfterSending));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.math.BigDecimal getValueToSend() {
        mono.embeddinator.Decimal __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_TransferAmount_get_ValueToSend(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret.getValue();
    }

    public java.math.BigDecimal getIdealValueRemainingAfterSending() {
        mono.embeddinator.Decimal __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_TransferAmount_get_IdealValueRemainingAfterSending(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret.getValue();
    }
}
