/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class UnsignedTransactionProposal implements mscorlib.system.collections.IStructuralEquatable {
    public com.sun.jna.Pointer __object;

    public UnsignedTransactionProposal(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    public UnsignedTransactionProposal(gwallet_backend_netstandard.gwallet.backend.Currency currency, java.lang.String originAddress, gwallet_backend_netstandard.gwallet.backend.TransferAmount amount, java.lang.String destinationAddress) {
        __object = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_UnsignedTransactionProposal_new(currency == null ? null : currency.__object, originAddress, amount == null ? null : amount.__object, destinationAddress);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String toString() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_UnsignedTransactionProposal_ToString(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public final boolean equals(gwallet_backend_netstandard.gwallet.backend.UnsignedTransactionProposal obj) {
        byte __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_UnsignedTransactionProposal_Equals(__object, obj == null ? null : obj.__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public gwallet_backend_netstandard.gwallet.backend.Currency getCurrency() {
        com.sun.jna.Pointer __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_UnsignedTransactionProposal_get_Currency(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new gwallet_backend_netstandard.gwallet.backend.Currency(__ret));
    }

    public java.lang.String getOriginAddress() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_UnsignedTransactionProposal_get_OriginAddress(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public gwallet_backend_netstandard.gwallet.backend.TransferAmount getAmount() {
        com.sun.jna.Pointer __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_UnsignedTransactionProposal_get_Amount(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new gwallet_backend_netstandard.gwallet.backend.TransferAmount(__ret));
    }

    public java.lang.String getDestinationAddress() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_UnsignedTransactionProposal_get_DestinationAddress(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
