/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend.bitcoin;

import mono.embeddinator.*;
import com.sun.jna.*;

public class BouncyCastleSecureRandomWrapperForNBitcoin implements nbitcoin.nbitcoin.IRandom {
    public com.sun.jna.Pointer __object;

    public BouncyCastleSecureRandomWrapperForNBitcoin(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    public BouncyCastleSecureRandomWrapperForNBitcoin() {
        __object = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_BouncyCastleSecureRandomWrapperForNBitcoin_new();
        mono.embeddinator.Runtime.checkExceptions();
    }
}
