/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend.bitcoin;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ElectrumServerReturningInternalErrorInJsonResponseException extends mscorlib.system.Exception {
    public ElectrumServerReturningInternalErrorInJsonResponseException(com.sun.jna.Pointer object) { super(object); }

    public ElectrumServerReturningInternalErrorInJsonResponseException(java.lang.String message, int code) {
        super((com.sun.jna.Pointer)null);
        __object = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_ElectrumServerReturningInternalErrorInJsonResponseException_new(message, code);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getErrorCode() {
        int __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_ElectrumServerReturningInternalErrorInJsonResponseException_get_ErrorCode(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
