/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend.bitcoin;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class Request implements mscorlib.system.collections.IStructuralEquatable {
    public com.sun.jna.Pointer __object;

    public Request(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    public java.lang.String toString() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_Request_ToString(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public final boolean equals(gwallet_backend_netstandard.gwallet.backend.bitcoin.Request obj) {
        byte __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_Request_Equals(__object, obj == null ? null : obj.__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public int getId() {
        int __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_Request_get_Id(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getMethod() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_Request_get_Method(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
