/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend.bitcoin;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class UnitConversion {
    public static java.math.BigDecimal fromSatoshiToBtc(long satoshis) {
        mono.embeddinator.Decimal __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_UnitConversion_FromSatoshiToBtc(satoshis);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret.getValue();
    }

    public static long fromBtcToSatoshis(java.math.BigDecimal btcAmount) {
        long __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_UnitConversion_FromBtcToSatoshis(new mono.embeddinator.Decimal(btcAmount));
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    static java.math.BigDecimal getHOW_MANY_SATOSHIS_ARE_THERE_IN_ONE_BTC() {
        mono.embeddinator.Decimal __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Bitcoin_UnitConversion_get_HOW_MANY_SATOSHIS_ARE_THERE_IN_ONE_BTC();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret.getValue();
    }
}
