/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package mscorlib.system;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Exception implements mscorlib.system.runtime.serialization.ISerializable, mscorlib.system.runtime.interopservices._Exception {
    public com.sun.jna.Pointer __object;

    public Exception(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    public Exception() {
        __object = mscorlib.Native_mscorlib.INSTANCE.System_Exception_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public Exception(java.lang.String message) {
        __object = mscorlib.Native_mscorlib.INSTANCE.System_Exception_new_1(message);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String toString() {
        java.lang.String __ret = mscorlib.Native_mscorlib.INSTANCE.System_Exception_ToString(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getMessage() {
        java.lang.String __ret = mscorlib.Native_mscorlib.INSTANCE.System_Exception_get_Message(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getStackTrace() {
        java.lang.String __ret = mscorlib.Native_mscorlib.INSTANCE.System_Exception_get_StackTrace(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getHelpLink() {
        java.lang.String __ret = mscorlib.Native_mscorlib.INSTANCE.System_Exception_get_HelpLink(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setHelpLink(java.lang.String value) {
        mscorlib.Native_mscorlib.INSTANCE.System_Exception_set_HelpLink(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getSource() {
        java.lang.String __ret = mscorlib.Native_mscorlib.INSTANCE.System_Exception_get_Source(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setSource(java.lang.String value) {
        mscorlib.Native_mscorlib.INSTANCE.System_Exception_set_Source(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    java.lang.String getRemoteStackTrace() {
        java.lang.String __ret = mscorlib.Native_mscorlib.INSTANCE.System_Exception_get_RemoteStackTrace(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public int getHResult() {
        int __ret = mscorlib.Native_mscorlib.INSTANCE.System_Exception_get_HResult(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    void setHResult(int value) {
        mscorlib.Native_mscorlib.INSTANCE.System_Exception_set_HResult(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    boolean getIsTransient() {
        byte __ret = mscorlib.Native_mscorlib.INSTANCE.System_Exception_get_IsTransient(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }
}
