/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package mscorlib.system.runtime.interopservices;

import mono.embeddinator.*;
import com.sun.jna.*;

public abstract interface _Exception {
    public java.lang.String toString();

    public java.lang.String getMessage();

    public java.lang.String getStackTrace();

    public java.lang.String getHelpLink();

    public void setHelpLink(java.lang.String value);

    public java.lang.String getSource();

    public void setSource(java.lang.String value);

    public com.sun.jna.Pointer __getObject();
}
