// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "mscorlib.h"
#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

mono_embeddinator_context_t __mono_context;
MonoImage* __mscorlib_dll_image;

static MonoClass* class_System_Exception = 0;
static MonoClass* class_System_Runtime_Serialization_ISerializable = 0;
static MonoClass* class_System_Runtime_InteropServices__Exception = 0;
static MonoClass* class_System_IEquatable_1 = 0;
static MonoClass* class_System_IComparable_1 = 0;
static MonoClass* class_System_IComparable = 0;
static MonoClass* class_System_IDisposable = 0;
static MonoClass* class_System_Collections_IStructuralEquatable = 0;
static MonoClass* class_System_Collections_IStructuralComparable = 0;

static void __initialize_mono()
{
    if (__mono_context.domain)
        return;
    mono_embeddinator_init(&__mono_context, "mono_embeddinator_binding");
}

static void __lookup_assembly_mscorlib_dll()
{
    if (__mscorlib_dll_image)
        return;
    __mscorlib_dll_image = mono_embeddinator_load_assembly(&__mono_context, "mscorlib.dll");
}

static void __lookup_class_System_Exception()
{
    if (class_System_Exception == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_Exception = mono_class_from_name(__mscorlib_dll_image, "System", "Exception");
    }
}

System_Exception* System_Exception_new()
{
    const char __method_name[] = "System.Exception:.ctor()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    System_Exception* __object = (System_Exception*) calloc(1, sizeof(System_Exception));
    MonoObject* __instance = mono_object_new(__mono_context.domain, class_System_Exception);
    mono_embeddinator_init_object(__object, __instance);

    MonoObject* __exception = 0;
    MonoObject* __result = mono_runtime_invoke(__method, __instance, 0, &__exception);

    if (__exception)
    {
        free(__object);
        mono_embeddinator_throw_exception(__exception);
        return 0;
    }

    return __object;
}

System_Exception* System_Exception_new_1(const char* message)
{
    const char __method_name[] = "System.Exception:.ctor(string)";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    System_Exception* __object = (System_Exception*) calloc(1, sizeof(System_Exception));
    MonoObject* __instance = mono_object_new(__mono_context.domain, class_System_Exception);
    mono_embeddinator_init_object(__object, __instance);

    void* __args[1];
    MonoString* __message_0 = (message) ? mono_string_new(__mono_context.domain, message) : 0;
    __args[0] = __message_0;

    MonoObject* __exception = 0;
    MonoObject* __result = mono_runtime_invoke(__method, __instance, __args, &__exception);

    if (__exception)
    {
        free(__object);
        mono_embeddinator_throw_exception(__exception);
        return 0;
    }

    return __object;
}

const char* System_Exception_ToString(System_Exception* object)
{
    const char __method_name[] = "System.Exception:ToString()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

const char* System_Exception_get_Message(System_Exception* object)
{
    const char __method_name[] = "System.Exception:get_Message()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

const char* System_Exception_get_StackTrace(System_Exception* object)
{
    const char __method_name[] = "System.Exception:get_StackTrace()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

const char* System_Exception_get_HelpLink(System_Exception* object)
{
    const char __method_name[] = "System.Exception:get_HelpLink()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

void System_Exception_set_HelpLink(System_Exception* object, const char* value)
{
    const char __method_name[] = "System.Exception:set_HelpLink(string)";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    void* __args[1];
    MonoString* __value_0 = (value) ? mono_string_new(__mono_context.domain, value) : 0;
    __args[0] = __value_0;

    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, __args, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);
}

const char* System_Exception_get_Source(System_Exception* object)
{
    const char __method_name[] = "System.Exception:get_Source()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

void System_Exception_set_Source(System_Exception* object, const char* value)
{
    const char __method_name[] = "System.Exception:set_Source(string)";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    void* __args[1];
    MonoString* __value_0 = (value) ? mono_string_new(__mono_context.domain, value) : 0;
    __args[0] = __value_0;

    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, __args, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);
}

const char* System_Exception_get_RemoteStackTrace(System_Exception* object)
{
    const char __method_name[] = "System.Exception:get_RemoteStackTrace()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoObject* __result = mono_runtime_invoke(__method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

int32_t System_Exception_get_HResult(System_Exception* object)
{
    const char __method_name[] = "System.Exception:get_HResult()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoObject* __result = mono_runtime_invoke(__method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    void* __unbox = mono_object_unbox(__result);

    return *((int32_t*)__unbox);
}

void System_Exception_set_HResult(System_Exception* object, int32_t value)
{
    const char __method_name[] = "System.Exception:set_HResult(int)";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    void* __args[1];
    __args[0] = &value;

    MonoObject* __exception = 0;
    MonoObject* __result = mono_runtime_invoke(__method, __instance, __args, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);
}

bool System_Exception_get_IsTransient(System_Exception* object)
{
    const char __method_name[] = "System.Exception:get_IsTransient()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoObject* __result = mono_runtime_invoke(__method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    void* __unbox = mono_object_unbox(__result);

    return *((bool*)__unbox);
}

static void __lookup_class_System_Runtime_Serialization_ISerializable()
{
    if (class_System_Runtime_Serialization_ISerializable == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_Runtime_Serialization_ISerializable = mono_class_from_name(__mscorlib_dll_image, "System.Runtime.Serialization", "ISerializable");
    }
}

static void __lookup_class_System_Runtime_InteropServices__Exception()
{
    if (class_System_Runtime_InteropServices__Exception == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_Runtime_InteropServices__Exception = mono_class_from_name(__mscorlib_dll_image, "System.Runtime.InteropServices", "_Exception");
    }
}

const char* System_Runtime_InteropServices__Exception_ToString(System_Runtime_InteropServices__Exception* object)
{
    const char __method_name[] = "System.Runtime.InteropServices._Exception:ToString()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Runtime_InteropServices__Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Runtime_InteropServices__Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

const char* System_Runtime_InteropServices__Exception_get_Message(System_Runtime_InteropServices__Exception* object)
{
    const char __method_name[] = "System.Runtime.InteropServices._Exception:get_Message()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Runtime_InteropServices__Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Runtime_InteropServices__Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

const char* System_Runtime_InteropServices__Exception_get_StackTrace(System_Runtime_InteropServices__Exception* object)
{
    const char __method_name[] = "System.Runtime.InteropServices._Exception:get_StackTrace()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Runtime_InteropServices__Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Runtime_InteropServices__Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

const char* System_Runtime_InteropServices__Exception_get_HelpLink(System_Runtime_InteropServices__Exception* object)
{
    const char __method_name[] = "System.Runtime.InteropServices._Exception:get_HelpLink()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Runtime_InteropServices__Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Runtime_InteropServices__Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

void System_Runtime_InteropServices__Exception_set_HelpLink(System_Runtime_InteropServices__Exception* object, const char* value)
{
    const char __method_name[] = "System.Runtime.InteropServices._Exception:set_HelpLink(string)";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Runtime_InteropServices__Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Runtime_InteropServices__Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    void* __args[1];
    MonoString* __value_0 = (value) ? mono_string_new(__mono_context.domain, value) : 0;
    __args[0] = __value_0;

    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, __args, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);
}

const char* System_Runtime_InteropServices__Exception_get_Source(System_Runtime_InteropServices__Exception* object)
{
    const char __method_name[] = "System.Runtime.InteropServices._Exception:get_Source()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Runtime_InteropServices__Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Runtime_InteropServices__Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    char* __string = mono_string_to_utf8((MonoString*) __result);

    return __string;
}

void System_Runtime_InteropServices__Exception_set_Source(System_Runtime_InteropServices__Exception* object, const char* value)
{
    const char __method_name[] = "System.Runtime.InteropServices._Exception:set_Source(string)";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_Runtime_InteropServices__Exception();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_Runtime_InteropServices__Exception);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    void* __args[1];
    MonoString* __value_0 = (value) ? mono_string_new(__mono_context.domain, value) : 0;
    __args[0] = __value_0;

    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, __args, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);
}

static void __lookup_class_System_Collections_IStructuralEquatable()
{
    if (class_System_Collections_IStructuralEquatable == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_Collections_IStructuralEquatable = mono_class_from_name(__mscorlib_dll_image, "System.Collections", "IStructuralEquatable");
    }
}

static void __lookup_class_System_Collections_IStructuralComparable()
{
    if (class_System_Collections_IStructuralComparable == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_Collections_IStructuralComparable = mono_class_from_name(__mscorlib_dll_image, "System.Collections", "IStructuralComparable");
    }
}

static void __lookup_class_System_IComparable()
{
    if (class_System_IComparable == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_IComparable = mono_class_from_name(__mscorlib_dll_image, "System", "IComparable");
    }
}

static void __lookup_class_System_IDisposable()
{
    if (class_System_IDisposable == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_IDisposable = mono_class_from_name(__mscorlib_dll_image, "System", "IDisposable");
    }
}

void System_IDisposable_Dispose(System_IDisposable* object)
{
    const char __method_name[] = "System.IDisposable:Dispose()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_System_IDisposable();
        __method = mono_embeddinator_lookup_method(__method_name, class_System_IDisposable);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);
}
