// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

MONO_EMBEDDINATOR_BEGIN_DECLS

typedef MonoEmbedObject NBitcoin_IRandom;

MONO_EMBEDDINATOR_API void NBitcoin_IRandom_GetBytes(NBitcoin_IRandom* object, uint8_t* output);

MONO_EMBEDDINATOR_END_DECLS
