// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

MONO_EMBEDDINATOR_BEGIN_DECLS

typedef MonoEmbedObject Newtonsoft_Json_JsonConverter;

MONO_EMBEDDINATOR_API bool Newtonsoft_Json_JsonConverter_get_CanRead(Newtonsoft_Json_JsonConverter* object);
MONO_EMBEDDINATOR_API bool Newtonsoft_Json_JsonConverter_get_CanWrite(Newtonsoft_Json_JsonConverter* object);

MONO_EMBEDDINATOR_END_DECLS
