// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "Newtonsoft.Json.h"
#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

mono_embeddinator_context_t __mono_context;
MonoImage* __Newtonsoft_Json_dll_image;

static MonoClass* class_Newtonsoft_Json_JsonConverter = 0;

static void __initialize_mono()
{
    if (__mono_context.domain)
        return;
    mono_embeddinator_init(&__mono_context, "mono_embeddinator_binding");
}

static void __lookup_assembly_Newtonsoft_Json_dll()
{
    if (__Newtonsoft_Json_dll_image)
        return;
    __Newtonsoft_Json_dll_image = mono_embeddinator_load_assembly(&__mono_context, "Newtonsoft.Json.dll");
}

static void __lookup_class_Newtonsoft_Json_JsonConverter()
{
    if (class_Newtonsoft_Json_JsonConverter == 0)
    {
        __initialize_mono();
        __lookup_assembly_Newtonsoft_Json_dll();
        class_Newtonsoft_Json_JsonConverter = mono_class_from_name(__Newtonsoft_Json_dll_image, "Newtonsoft.Json", "JsonConverter");
    }
}

bool Newtonsoft_Json_JsonConverter_get_CanRead(Newtonsoft_Json_JsonConverter* object)
{
    const char __method_name[] = "Newtonsoft.Json.JsonConverter:get_CanRead()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_Newtonsoft_Json_JsonConverter();
        __method = mono_embeddinator_lookup_method(__method_name, class_Newtonsoft_Json_JsonConverter);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    void* __unbox = mono_object_unbox(__result);

    return *((bool*)__unbox);
}

bool Newtonsoft_Json_JsonConverter_get_CanWrite(Newtonsoft_Json_JsonConverter* object)
{
    const char __method_name[] = "Newtonsoft.Json.JsonConverter:get_CanWrite()";
    static MonoMethod *__method = 0;

    if (!__method)
    {
        __lookup_class_Newtonsoft_Json_JsonConverter();
        __method = mono_embeddinator_lookup_method(__method_name, class_Newtonsoft_Json_JsonConverter);
    }

    MonoObject* __instance = mono_gchandle_get_target(object->_handle);
    MonoObject* __exception = 0;
    MonoMethod* __virtual_method = mono_object_get_virtual_method(__instance, __method);
    MonoObject* __result = mono_runtime_invoke(__virtual_method, __instance, 0, &__exception);

    if (__exception)
        mono_embeddinator_throw_exception(__exception);

    void* __unbox = mono_object_unbox(__result);

    return *((bool*)__unbox);
}
