/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package nbitcoin;

import mono.embeddinator.*;
import com.sun.jna.*;
public interface Native_NBitcoin extends com.sun.jna.Library
{
    Native_NBitcoin INSTANCE = 
        mono.embeddinator.Runtime.loadLibrary("NBitcoin", Native_NBitcoin.class);

}
