/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package nbitcoin.nbitcoin;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class IRandomImpl implements nbitcoin.nbitcoin.IRandom {
    public com.sun.jna.Pointer __object;

    public IRandomImpl(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

}
