/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package nbitcoin.nbitcoin;

import mono.embeddinator.*;
import com.sun.jna.*;

public abstract interface IRandom {
    public com.sun.jna.Pointer __getObject();
}
