/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package newtonsoft_json.newtonsoft.json;

import mono.embeddinator.*;
import com.sun.jna.*;

public abstract class JsonConverter {
    public com.sun.jna.Pointer __object;

    public JsonConverter(com.sun.jna.Pointer object) { this.__object = object; }

    public boolean getCanRead() {
        byte __ret = newtonsoft_json.Native_Newtonsoft_Json.INSTANCE.Newtonsoft_Json_JsonConverter_get_CanRead(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public boolean getCanWrite() {
        byte __ret = newtonsoft_json.Native_Newtonsoft_Json.INSTANCE.Newtonsoft_Json_JsonConverter_get_CanWrite(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }
}
