/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend.ether;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ServerTimedOutException extends gwallet_backend_netstandard.gwallet.backend.ether.ConnectionUnsuccessfulException {
    public ServerTimedOutException(com.sun.jna.Pointer object) { super(object); }

    public ServerTimedOutException(java.lang.String message) {
        super((com.sun.jna.Pointer)null);
        __object = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Ether_ServerTimedOutException_new(message);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
