/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend.ether;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ServerCannotBeResolvedException extends gwallet_backend_netstandard.gwallet.backend.ether.ConnectionUnsuccessfulException {
    public ServerCannotBeResolvedException(com.sun.jna.Pointer object) { super(object); }

}
