/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package gwallet_backend_netstandard.gwallet.backend.ether;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class TransactionMetadata implements mscorlib.system.collections.IStructuralEquatable, gwallet_backend_netstandard.gwallet.backend.IBlockchainFeeInfo {
    public com.sun.jna.Pointer __object;

    public TransactionMetadata(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    public TransactionMetadata(gwallet_backend_netstandard.gwallet.backend.ether.MinerFee fee, long transactionCount) {
        __object = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Ether_TransactionMetadata_new(fee == null ? null : fee.__object, transactionCount);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String toString() {
        java.lang.String __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Ether_TransactionMetadata_ToString(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public final boolean equals(gwallet_backend_netstandard.gwallet.backend.ether.TransactionMetadata obj) {
        byte __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Ether_TransactionMetadata_Equals(__object, obj == null ? null : obj.__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public gwallet_backend_netstandard.gwallet.backend.ether.MinerFee getFee() {
        com.sun.jna.Pointer __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Ether_TransactionMetadata_get_Fee(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new gwallet_backend_netstandard.gwallet.backend.ether.MinerFee(__ret));
    }

    public long getTransactionCount() {
        long __ret = gwallet_backend_netstandard.Native_GWallet_Backend_NetStandard.INSTANCE.GWallet_Backend_Ether_TransactionMetadata_get_TransactionCount(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
