/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package newtonsoft_json;

import mono.embeddinator.*;
import com.sun.jna.*;

public interface Native_Newtonsoft_Json extends com.sun.jna.Library
{
    Native_Newtonsoft_Json INSTANCE = 
        mono.embeddinator.Runtime.loadLibrary("Newtonsoft.Json", Native_Newtonsoft_Json.class);

    public byte Newtonsoft_Json_JsonConverter_get_CanRead(com.sun.jna.Pointer object);
    public byte Newtonsoft_Json_JsonConverter_get_CanWrite(com.sun.jna.Pointer object);
}
